### ISSUE TITLE
Error while launching ptc2

### ISSUE THREAD

**Issue by syrius01** [Kitryn/PTCAccount2#11]
C:\Users\syrius>ptc2
Creating new account:
Attempting to create user 66BTWL6Oub5Or6E:f4RydUP2S92ljmi. Opening browser...
Traceback (most recent call last):
  File "C:\Python27\Scripts\ptc2-script.py", line 9, in <module>
    load_entry_point('PTCAccount2==2.0.2', 'console_scripts', 'ptc2')()
  File "c:\python27\lib\site-packages\ptcaccount2\console.py", line 47, in entry
    account_info = ptcaccount2.random_account(args.username, args.password, args.email, args.birthday)
  File "c:\python27\lib\site-packages\ptcaccount2\accounts.py", line 210, in random_account
    account_created = create_account(try_username, password, try_email, try_birthday)
  File "c:\python27\lib\site-packages\ptcaccount2\accounts.py", line 116, in create_account
    driver = webdriver.Chrome()
  File "c:\python27\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 62, in **init**
    self.service.start()
  File "c:\python27\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x00000000033C2400>> ignored

Any solutions for fixing this issue ?

Thanks for your time !

**Comment by smc87** [comment]
'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by syrius01** [comment]
resolved. thx smc87 !
