### ISSUE TITLE
Error while creating

### ISSUE THREAD

**Issue by RubenHiem** [Kitryn/PTCAccount2#32]
What is the problem here?

Creating new account(s):
Attempting to create user Og9IS1RO7ppoSQ3:3uai203H6g8HBp9. Opening browser...
Traceback (most recent call last):
  File "/usr/bin/ptc2", line 9, in <module>
    load_entry_point('PTCAccount2==2.0.8', 'console_scripts', 'ptc2')()
  File "/usr/lib/python2.7/site-packages/ptcaccount2/console.py", line 72, in entry
    args.username, args.password, args.email, args.birthday, args.email_tag)
  File "/usr/lib/python2.7/site-packages/ptcaccount2/accounts.py", line 238, in random_account
    account_created = create_account(try_username, password, use_email, try_birthday)
  File "/usr/lib/python2.7/site-packages/ptcaccount2/accounts.py", line 118, in create_account
    driver = webdriver.Chrome()
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in **init**
    desired_capabilities=desired_capabilities)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 90, in **init**
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Could not find default Chrome binary

**Comment by Kitryn** [comment]
Looks like Google chrome (the actual browser) is not installed. Do you have it installed?

**Comment by RubenHiem** [comment]
Thanks @Kitryn, i have now install google chrome, google-chrome-stable-52.0.2743.116-1.x86_64. Same error.

**Comment by Kitryn** [comment]
Is Google Chrome installed into the default directory, or did you specify a directory during installation?

**Comment by RubenHiem** [comment]
Default directory, its on my centos 7 vps

**Comment by RubenHiem** [comment]
Now i'm gonna try it on my mac

**Comment by Kitryn** [comment]
I don't have much experience with Linux, unfortunately, but does [this stackoverflow](https://stackoverflow.com/questions/18674092/how-to-implement-chromedriver-in-selenium-in-linux-platform) question help?

> ## OS          Expected Location of Chrome
> 
> Linux          /usr/bin/google-chrome

**Comment by RubenHiem** [comment]
This is what my mac sais: 

Command "/usr/bin/python -u -c "import setuptools, tokenize;**file**='/var/folders/25/w3klqfxj2n71sql_qjw9w8k00000gn/T/pip-34soWG-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/25/w3klqfxj2n71sql_qjw9w8k00000gn/T/pip-_7XBSL-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /var/folders/25/w3klqfxj2n71sql_qjw9w8k00000gn/T/pip-34soWG-build/

**Comment by Kitryn** [comment]
Which stage are you at? Python installation, or installing this package?

**Comment by RubenHiem** [comment]
nvm its solved! thanks for your help and program!

**Comment by Kitryn** [comment]
Glad to hear!
