### ISSUE TITLE
Runtime.evaluate missing 'wasThrown'

### ISSUE THREAD

**Issue by Mickey32111** [Kitryn/PTCAccount2#39]
Whenever I attempt to run the script on Mac OS X 10 I get the following error:

`Creating new account(s):
Attempting to create user ak2lr6MDbXnB00R:RllaHIQz3JQSvBW. Opening browser...
Summary of accounts created:
Traceback (most recent call last):
  File "/usr/local/bin/ptc2", line 11, in <module>
    load_entry_point('PTCAccount2==2.0.9', 'console_scripts', 'ptc2')()
  File "/usr/local/lib/python2.7/site-packages/ptcaccount2/console.py", line 72, in entry
    args.username, args.password, args.email, args.birthday, args.email_tag)
  File "/usr/local/lib/python2.7/site-packages/ptcaccount2/accounts.py", line 239, in random_account
    account_created = create_account(try_username, password, use_email, try_birthday)
  File "/usr/local/lib/python2.7/site-packages/ptcaccount2/accounts.py", line 118, in create_account
    driver = webdriver.Chrome()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: session not created exception
from unknown error: Runtime.evaluate missing 'wasThrown'
  (Session info: chrome=54.0.2837.0)
  (Driver info: chromedriver=2.23.409710 (0c4084804897ac45b5ff65a690ec6583b97225c0),platform=Mac OS X 10.12.0 x86_64)`

**Comment by Kitryn** [comment]
The current stable version of Chrome is v52, and you're running the dev release channel of Chrome (v54); when I tried running this script with v54 it crashed as well, so probably ChromeDriver is not compatible with the dev channel of Chrome.  Maybe try downgrading to the stable channel?

I should probably work on a way to let users use Firefox instead, but I've been busy these days :/

**Comment by Kitryn** [comment]
Closing from inactivity.
